# Generated by Django 4.2.16 on 2024-12-06 05:57

from django.db import migrations, models
import job_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a profile image', null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='qualifications',
            field=models.TextField(help_text='List your academic qualifications', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='domain_preferences',
            field=models.ManyToManyField(blank=True, help_text='Choose preferred domains', null=True, to='job_portal.domain'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Select applicable skills', null=True, to='job_portal.skill'),
        ),
    ]
