# Generated by Django 4.2.16 on 2024-12-06 10:48

import django.core.validators
from django.db import migrations, models
import job_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0004_companyprofile_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Provide your LinkedIn profile URL', max_length=255, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='stream',
            field=models.CharField(help_text='Enter your field of study or specialization', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mobile',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10-15 digits).', regex='^\\+?\\d{10,15}$')]),
        ),
    ]
