# Generated by Django 4.2.16 on 2024-12-09 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0005_studentprofile_linkedin_url_studentprofile_stream_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mobile',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10 digits).', regex='^\\+?\\d{10}$')]),
        ),
    ]
