# Generated by Django 4.2.16 on 2024-12-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0006_remove_companyprofile_twitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='confirm_password',
            field=models.CharField(help_text='Re-enter the password for confirmation', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='password',
            field=models.CharField(help_text='Enter a secure password', max_length=128, null=True),
        ),
    ]
