# Generated by Django 4.2.16 on 2024-12-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0007_companyprofile_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='confirm_password',
            field=models.CharField(help_text='Re-enter the password for confirmation', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='password',
            field=models.CharField(help_text='Enter a secure password', max_length=128, null=True),
        ),
    ]
