# Generated by Django 4.2.16 on 2024-12-16 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0008_studentprofile_confirm_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='domain_preferences',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
