# Generated by Django 4.2.16 on 2024-12-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(default='Video Editor', max_length=100)),
                ('availability', models.CharField(choices=[('immediate', 'Yes, I am available to join immediately'), ('notice', 'No, I am currently on notice period'), ('serve-notice', 'No, I will have to serve notice period'), ('other', 'Other')], default='immediate', max_length=20)),
                ('has_laptop', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3)),
                ('english_proficiency', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('custom_resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
