# Generated by Django 4.2.16 on 2024-12-10 08:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=150, null=True)),
                ('internship', models.CharField(blank=True, max_length=150, null=True)),
                ('skills', models.CharField(blank=True, max_length=300, null=True)),
                ('payment', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=80, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='applicant_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='application',
            name='custom_resume',
        ),
        migrations.RemoveField(
            model_name='application',
            name='date_applied',
        ),
        migrations.RemoveField(
            model_name='application',
            name='english_proficiency',
        ),
        migrations.RemoveField(
            model_name='application',
            name='has_laptop',
        ),
        migrations.RemoveField(
            model_name='application',
            name='job_title',
        ),
        migrations.AddField(
            model_name='application',
            name='applied_at',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='mobile_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='qualification',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='year_of_graduation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications_list', to='internship.company'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='internship.user'),
        ),
    ]
