# Generated by Django 4.2.16 on 2024-12-10 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_company_user_remove_application_applicant_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
