# Generated by Django 4.2.16 on 2024-12-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_alter_application_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='application',
            table='Application',
        ),
        migrations.AlterModelTable(
            name='company',
            table='Company',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
