# Generated by Django 4.2.16 on 2024-12-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_studentprofile_delete_application_delete_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='Qualifications',
            new_name='education_level',
        ),
    ]
