# Generated by Django 4.2.16 on 2024-12-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0006_rename_qualifications_studentprofile_education_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='education_level',
            new_name='qualifications',
        ),
    ]
