# Generated by Django 4.2.16 on 2024-12-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0008_remove_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('industry_type', models.CharField(choices=[('IT', 'Information Technology'), ('Finance', 'Finance'), ('HR', 'Human Resources'), ('Marketing', 'Marketing')], max_length=50)),
                ('number_of_employees', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('profile_image', models.ImageField(upload_to='organization_images/')),
                ('website_url', models.URLField()),
                ('business_registration_doc', models.FileField(upload_to='registration_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
