"""new column four added

Revision ID: 092a03ffda73
Revises: 11688d770278
Create Date: 2024-12-10 06:36:21.053312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092a03ffda73'
down_revision = '11688d770278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('skills', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('about_internship', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('certification_courses', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('who_can_apply', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('no_of_vacancies', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('about_talentconnect', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('about_talentconnect')
        batch_op.drop_column('no_of_vacancies')
        batch_op.drop_column('who_can_apply')
        batch_op.drop_column('certification_courses')
        batch_op.drop_column('about_internship')
        batch_op.drop_column('skills')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
