"""new column duration added

Revision ID: 11688d770278
Revises: ca58891a0258
Create Date: 2024-12-10 05:40:55.639508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11688d770278'
down_revision = 'ca58891a0258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.String(length=50), nullable=True))
        batch_op.drop_column('location')
        batch_op.drop_column('skills')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', mysql.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('location', mysql.VARCHAR(length=150), nullable=False))
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
