"""corrected the string values

Revision ID: 812b38295842
Revises: 092a03ffda73
Create Date: 2024-12-10 07:59:32.727460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '812b38295842'
down_revision = '092a03ffda73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('certification_courses',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=50000),
               existing_nullable=True)
        batch_op.alter_column('who_can_apply',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=20000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('who_can_apply',
               existing_type=sa.String(length=20000),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('certification_courses',
               existing_type=sa.String(length=50000),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
